### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by hadi94941** [jatintiwari0/FbCreator#3]
i have face this error :
Traceback (most recent call last):
  File "C:\Users\ymale\Downloads\FbCreator-main\FbCreator.py", line 90, in <module>
    register_facebook_account(email, password, first_name, last_name, birthday)
  File "C:\Users\ymale\Downloads\FbCreator-main\FbCreator.py", line 66, in register_facebook_account
    id=reg['new_user_id']
KeyError: 'new_user_id'
   what can i do please

**Comment by bhaikyahaix** [comment]
I think you edit code

**Comment by bhaikyahaix** [comment]
Right 👍🏻

**Comment by jattin1** [comment]
I think you edit the code that why is problem come
