### ISSUE TITLE
error

### ISSUE THREAD

**Issue by przemek327** [jatintiwari0/FbCreator#4]
[+] How Many Accounts You Want:  1

Traceback (most recent call last):
  File "/root/FbCreator/FbCreator.py", line 90, in <module>
    register_facebook_account(email, password, first_name, last_name, birthday)
  File "/root/FbCreator/FbCreator.py", line 66, in register_facebook_account
    id=reg['new_user_id']
KeyError: 'new_user_id'

**Comment by jattin1** [comment]
I think temp mail api key is updated that why this problem come

**Comment by przemek327** [comment]
can you update it?

**Comment by jattin1** [comment]
Ok
